/**
 * Generates supabase/seed.sql from the TypeScript demo dataset (single source of truth).
 * Deterministic UUIDv5 ids are derived from the dataset ids so re-running is stable.
 *   npm run seed:sql
 */
import { writeFileSync } from 'node:fs';
import { SEED } from '../src/data/seed';
import type { Citation, Entity } from '../src/lib/domain/types';
import { seedUuid as uuidv5 } from '../src/lib/data/seed-ids';

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') return `'${v.replace(/'/g, "''")}'`;
  return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
};
const arr = (v: string[], type = 'text') => (v.length ? `array[${v.map(q).join(', ')}]::${type}[]` : `'{}'::${type}[]`);
const id = (key: string) => q(uuidv5(key));

const out: string[] = [
  '-- GENERATED by scripts/generate-seed-sql.ts — do not edit by hand.',
  '-- Demo dataset: every row is pending human review.',
  'begin;',
];

const citations = (table: string, targetKey: string, list: Citation[]) =>
  list.forEach((c, i) =>
    out.push(
      `insert into public.citations (source_id, target_table, target_id, locator, ordinal) values (${id('source:' + c.sourceId)}, ${q(table)}, ${id(targetKey)}, ${q(c.locator ?? null)}, ${i}) on conflict do nothing;`,
    ),
  );

for (const s of SEED.sources)
  out.push(
    `insert into public.sources (id, key, kind, title, publisher, url, doi, pmid, language, notes, added_at) values (${id('source:' + s.id)}, ${q(s.id)}, ${q(s.kind)}, ${q(s.title)}, ${q(s.publisher)}, ${q(s.url)}, ${q(s.doi ?? null)}, ${q(s.pmid ?? null)}, ${q(s.language)}, ${q(s.notes ?? null)}, ${q(s.addedAt)});`,
  );

for (const r of SEED.regions)
  out.push(
    `insert into public.regions (id, slug, name, level, parent_id, code) values (${id('region:' + r.slug)}, ${q(r.slug)}, ${q(r.name)}, ${q(r.level)}, ${r.parentSlug ? id('region:' + r.parentSlug) : 'null'}, ${q(r.code ?? null)});`,
  );

const sci = (e: Entity) => (e.type === 'plant' ? e.plant.scientificName : e.type === 'mushroom' ? e.mushroom.scientificName : e.type === 'food' ? e.food.scientificName ?? null : null);

for (const e of SEED.entities) {
  out.push(
    `insert into public.entities (id, entity_type, slug, name, scientific_name, summary, simple_summary, tags, review_status, updated_at) values (${id(e.id)}, ${q(e.type)}, ${q(e.slug)}, ${q(e.name)}, ${q(sci(e))}, ${q(e.summary ?? null)}, ${q(e.simpleSummary ?? null)}, ${arr(e.tags)}, ${q(e.reviewStatus)}, ${q(e.updatedAt)});`,
  );
  switch (e.type) {
    case 'plant': {
      const p = e.plant;
      out.push(
        `insert into public.plants (entity_id, family, synonyms, botanical_description, distribution, legal_notes, name_ambiguity) values (${id(e.id)}, ${q(p.family)}, ${arr(p.synonyms)}, ${q(p.botanicalDescription ?? null)}, ${q(p.distribution ?? null)}, ${q(p.legalNotes ?? null)}, ${q(p.nameAmbiguity ?? null)});`,
      );
      p.partsUsed.forEach((part, i) => out.push(`insert into public.plant_parts (entity_id, part, ordinal) values (${id(e.id)}, ${q(part)}, ${i});`));
      p.preparations.forEach((pr, i) => {
        const key = `${e.id}:prep:${i}`;
        out.push(`insert into public.preparations (id, entity_id, name, description, context, ordinal) values (${id(key)}, ${id(e.id)}, ${q(pr.name)}, ${q(pr.description)}, ${q(pr.context)}, ${i});`);
        citations('preparations', key, pr.citations);
      });
      break;
    }
    case 'mushroom': {
      const m = e.mushroom;
      out.push(
        `insert into public.mushrooms (entity_id, family, synonyms, edibility, description, distribution) values (${id(e.id)}, ${q(m.family)}, ${arr(m.synonyms)}, ${q(m.edibility)}, ${q(m.description ?? null)}, ${q(m.distribution ?? null)});`,
      );
      break;
    }
    case 'food':
      out.push(`insert into public.foods (entity_id, family, food_group, nutrients) values (${id(e.id)}, ${q(e.food.family ?? null)}, ${q(e.food.foodGroup)}, ${q(e.food.nutrients)});`);
      break;
    case 'compound': {
      const c = e.compound;
      out.push(
        `insert into public.compounds (entity_id, formula, compound_class, pubchem_query, bioavailability, mechanisms_investigated) values (${id(e.id)}, ${q(c.formula ?? null)}, ${arr(c.compoundClass)}, ${q(c.pubchemQuery)}, ${q(c.bioavailability ?? null)}, ${q(c.mechanismsInvestigated)});`,
      );
      break;
    }
    case 'condition':
      // parent_id is set in a second pass (parents may come later)
      out.push(`insert into public.conditions (entity_id, kind, is_cancer, icd10) values (${id(e.id)}, ${q(e.condition.kind)}, ${q(e.condition.isCancer)}, ${q(e.condition.icd10 ?? null)});`);
      break;
    case 'medication':
      out.push(
        `insert into public.medications (entity_id, drug_class, atc_code, categories) values (${id(e.id)}, ${q(e.medication.drugClass)}, ${q(e.medication.atcCode ?? null)}, ${arr(e.medication.categories, 'medication_category')});`,
      );
      break;
  }
  e.aliases.forEach((a, i) =>
    out.push(
      `insert into public.entity_aliases (entity_id, name, lang, kind, region_id, ordinal) values (${id(e.id)}, ${q(a.name)}, ${q(a.lang)}, ${q(a.kind)}, ${a.region ? id('region:' + a.region) : 'null'}, ${i}) on conflict do nothing;`,
    ),
  );
  e.regions.forEach((r, i) => out.push(`insert into public.entity_regions (entity_id, region_id, ordinal) values (${id(e.id)}, ${id('region:' + r)}, ${i});`));
  e.safety.forEach((s, i) => {
    const key = `${e.id}:safety:${i}`;
    out.push(`insert into public.safety_warnings (id, entity_id, topic, status, text, ordinal, review_status) values (${id(key)}, ${id(e.id)}, ${q(s.topic)}, ${q(s.status)}, ${q(s.text)}, ${i}, ${q(s.reviewStatus)});`);
    citations('safety_warnings', key, s.citations);
  });
  citations('entities', e.id, e.citations);
}

for (const e of SEED.entities)
  if (e.type === 'condition' && e.condition.parentSlug)
    out.push(`update public.conditions set parent_id = ${id('condition:' + e.condition.parentSlug)} where entity_id = ${id(e.id)};`);

for (const r of SEED.relations) {
  out.push(
    `insert into public.entity_relations (id, subject_id, predicate, object_id, note, review_status) values (${id(r.id)}, ${id(r.subjectId)}, ${q(r.predicate)}, ${id(r.objectId)}, ${q(r.note ?? null)}, ${q(r.reviewStatus)});`,
  );
  citations('entity_relations', r.id, r.citations);
}

for (const c of SEED.claims) {
  out.push(
    `insert into public.evidence_claims (id, subject_id, condition_id, context, level, category, study_types, human_evidence, statement, simple, what_we_know, what_we_dont_know, under_investigation, risks, limitations, research_doses, review_status, updated_at) values (${id(c.id)}, ${id(c.subjectId)}, ${c.conditionId ? id(c.conditionId) : 'null'}, ${q(c.context)}, ${q(c.level)}, ${q(c.category)}, ${arr(c.studyTypes, 'study_type')}, ${q(c.humanEvidence)}, ${q(c.statement)}, ${q(c.simple)}, ${q(c.whatWeKnow)}, ${q(c.whatWeDontKnow)}, ${q(c.underInvestigation)}, ${q(c.risks)}, ${q(c.limitations)}, ${q(c.researchDoses ?? null)}, ${q(c.reviewStatus)}, ${q(c.updatedAt)});`,
  );
  citations('evidence_claims', c.id, c.citations);
}

for (const i of SEED.interactions) {
  out.push(
    `insert into public.interactions (id, agent_id, medication_id, kind, severity, effect, mechanism, level, review_status, updated_at) values (${id(i.id)}, ${id(i.agentId)}, ${id(i.medicationId)}, ${q(i.kind)}, ${q(i.severity)}, ${q(i.effect)}, ${q(i.mechanism ?? null)}, ${q(i.level)}, ${q(i.reviewStatus)}, ${q(i.updatedAt)});`,
  );
  citations('interactions', i.id, i.citations);
}

for (const t of SEED.traditionalUses) {
  out.push(
    `insert into public.traditional_knowledge (id, entity_id, region_id, culture, use, preparation, part_used, documentation, review_status, updated_at) values (${id(t.id)}, ${id(t.entityId)}, ${id('region:' + t.regionSlug)}, ${q(t.culture ?? null)}, ${q(t.use)}, ${q(t.preparation ?? null)}, ${q(t.partUsed ?? null)}, ${q(t.documentation)}, ${q(t.reviewStatus)}, ${q(t.updatedAt)});`,
  );
  citations('traditional_knowledge', t.id, t.citations);
}

// Example literature watch: detects new PubMed records for review (never auto-published).
out.push(
  `insert into public.literature_watches (label, pubmed_query, entity_ids) values ('Curcumina + cáncer colorrectal', 'curcumin[tiab] AND (colorectal neoplasms[mh] OR colorectal cancer[tiab])', array[${id('compound:curcumina')}, ${id('condition:cancer-colorrectal')}]::uuid[]);`,
);

out.push('commit;', '');
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n'));
console.log(`seed.sql written: ${out.length} statements`);
