import type { LucideIcon } from 'lucide-react';
import {
  UtensilsCrossed, Store, Shirt, Footprints, Gem, Scissors,
  Wrench, Hammer, Pill, Briefcase, Laptop, ShoppingBasket, Coffee, Croissant,
  HardHat, PawPrint, Dumbbell, Paperclip, Shirt as TextileIcon, Palette, ParkingSquare,
  Car, WashingMachine, Flower, Glasses, SmilePlus, Stethoscope, Scale, Calculator,
  PartyPopper, Sofa, Trophy, ToyBrick, BookOpen, Wine, Wheat, Beef, Carrot,
  Hotel, BusFront, GraduationCap, Hand, Flower as SpaIcon, Camera, Printer,
  ShieldCheck, Bike, Store as OtherIcon, Scissors as BarberIcon,
} from 'lucide-react';

export const APP_NAME = 'Conecta MX';
export const APP_TAGLINE = 'Consigue más clientes. Mide tu inversión. Crece.';

export const MUNICIPALITIES: string[] = [
  'Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas',
  'Chihuahua',
  'Ciudad de México',
  'Coahuila',
  'Colima',
  'Durango',
  'Estado de México',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'Michoacán',
  'Morelos',
  'Nayarit',
  'Nuevo León',
  'Oaxaca',
  'Puebla',
  'Querétaro',
  'Quintana Roo',
  'San Luis Potosí',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz',
  'Yucatán',
  'Zacatecas',
];

export interface CategoryDef {
  name: string;
  icon: LucideIcon;
}

export const CATEGORIES: CategoryDef[] = [
  { name: 'Taquerías', icon: UtensilsCrossed },
  { name: 'Restaurantes', icon: UtensilsCrossed },
  { name: 'Ropa y Moda', icon: Shirt },
  { name: 'Zapaterías', icon: Footprints },
  { name: 'Joyerías', icon: Gem },
  { name: 'Estéticas', icon: Scissors },
  { name: 'Barberías', icon: BarberIcon },
  { name: 'Talleres', icon: Wrench },
  { name: 'Ferreterías', icon: Hammer },
  { name: 'Farmacias', icon: Pill },
  { name: 'Servicios', icon: Briefcase },
  { name: 'Tecnología', icon: Laptop },
  { name: 'Abarrotes', icon: ShoppingBasket },
  { name: 'Cafeterías', icon: Coffee },
  { name: 'Panaderías', icon: Croissant },
  { name: 'Construcción', icon: HardHat },
  { name: 'Mascotas', icon: PawPrint },
  { name: 'Gimnasios', icon: Dumbbell },
  { name: 'Papelerías', icon: Paperclip },
  { name: 'Textil', icon: TextileIcon },
  { name: 'Artesanías', icon: Palette },
  { name: 'Estacionamientos', icon: ParkingSquare },
  { name: 'Automotriz', icon: Car },
  { name: 'Lavanderías', icon: WashingMachine },
  { name: 'Florerías', icon: Flower },
  { name: 'Ópticas', icon: Glasses },
  { name: 'Dentistas', icon: SmilePlus },
  { name: 'Médicos', icon: Stethoscope },
  { name: 'Abogados', icon: Scale },
  { name: 'Contadores', icon: Calculator },
  { name: 'Eventos', icon: PartyPopper },
  { name: 'Muebles', icon: Sofa },
  { name: 'Deportes', icon: Trophy },
  { name: 'Jugueterías', icon: ToyBrick },
  { name: 'Librerías', icon: BookOpen },
  { name: 'Vinaterías', icon: Wine },
  { name: 'Tortillerías', icon: Wheat },
  { name: 'Carnicerías', icon: Beef },
  { name: 'Verdulerías', icon: Carrot },
  { name: 'Hoteles', icon: Hotel },
  { name: 'Transporte', icon: BusFront },
  { name: 'Educación', icon: GraduationCap },
  { name: 'Belleza', icon: Hand },
  { name: 'Spa', icon: SpaIcon },
  { name: 'Fotografía', icon: Camera },
  { name: 'Imprentas', icon: Printer },
  { name: 'Seguros', icon: ShieldCheck },
  { name: 'Bicicletas', icon: Bike },
  { name: 'Otros', icon: OtherIcon },
];

export const CONTRACT_TYPES = [
  'Tiempo completo',
  'Medio tiempo',
  'Por hora',
  'Temporal',
  'Prácticas',
  'Freelance',
];

export const PLAN_LABELS: Record<string, string> = {
  free: 'Gratis',
  featured: 'Destacado',
  premium: 'Premium',
};

export const PLAN_LIMITS: Record<string, number> = {
  free: 10,
  featured: 50,
  premium: Infinity,
};

export const PLAN_PRICES: Record<string, number> = {
  free: 0,
  featured: 49,
  premium: 99,
};

export const FOUNDING_THRESHOLD = 30;

export const EVENT_CATEGORIES = [
  'Música', 'Cultura', 'Gastronomía', 'Deportes', 'Familia', 'Religioso', 'Feria', 'Arte', 'Educación', 'Otros',
];

export const PUBLICATION_TAGS: Record<string, { label: string; icon: string; color: string }> = {
  new: { label: 'Nuevo', icon: 'Flame', color: 'bg-orange-500' },
  featured: { label: 'Destacado', icon: 'Star', color: 'bg-amber-400' },
  offer: { label: 'Oferta', icon: 'BadgeDollarSign', color: 'bg-emerald-500' },
  last_units: { label: 'Últimas piezas', icon: 'AlertTriangle', color: 'bg-rose-500' },
  promotion: { label: 'Promoción', icon: 'PartyPopper', color: 'bg-purple-500' },
};

export const REPORT_REASONS: { value: string; label: string }[] = [
  { value: 'fake', label: 'Negocio falso' },
  { value: 'wrong_info', label: 'Información incorrecta' },
  { value: 'inappropriate', label: 'Fotos inapropiadas' },
  { value: 'fraud', label: 'Fraude' },
];

export const SMART_SEARCH_MAP: Record<string, string[]> = {
  tacos: ['Taquerías', 'Restaurantes'],
  taco: ['Taquerías', 'Restaurantes'],
  taqueria: ['Taquerías'],
  comida: ['Restaurantes', 'Taquerías', 'Cafeterías', 'Panaderías'],
  restaurant: ['Restaurantes'],
  restaurante: ['Restaurantes'],
  cafe: ['Cafeterías'],
  pan: ['Panaderías'],
  panaderia: ['Panaderías'],
  ropa: ['Ropa y Moda', 'Zapaterías'],
  moda: ['Ropa y Moda', 'Zapaterías', 'Joyerías'],
  zapatos: ['Zapaterías'],
  zapato: ['Zapaterías'],
  joyeria: ['Joyerías'],
  joyería: ['Joyerías'],
  belleza: ['Estéticas', 'Barberías', 'Spa', 'Belleza'],
  estetica: ['Estéticas'],
  estética: ['Estéticas'],
  barberia: ['Barberías'],
  barbería: ['Barberías'],
  pelo: ['Estéticas', 'Barberías'],
  corte: ['Estéticas', 'Barberías'],
  farmacia: ['Farmacias'],
  medicina: ['Médicos', 'Farmacias', 'Dentistas'],
  doctor: ['Médicos'],
  doctora: ['Médicos'],
  dentista: ['Dentistas'],
  dientes: ['Dentistas'],
  abogado: ['Abogados'],
  abogada: ['Abogados'],
  contador: ['Contadores'],
  contadora: ['Contadores'],
  impuestos: ['Contadores'],
  auto: ['Automotriz'],
  coche: ['Automotriz'],
  carro: ['Automotriz'],
  mecanico: ['Automotriz', 'Talleres'],
  mecánico: ['Automotriz', 'Talleres'],
  taller: ['Talleres', 'Automotriz'],
  ferreteria: ['Ferreterías'],
  ferretería: ['Ferreterías'],
  herramientas: ['Ferreterías'],
  construccion: ['Construcción', 'Ferreterías'],
  construcción: ['Construcción', 'Ferreterías'],
  mascota: ['Mascotas'],
  perro: ['Mascotas'],
  gato: ['Mascotas'],
  veterinario: ['Mascotas', 'Médicos'],
  gimnasio: ['Gimnasios'],
  gym: ['Gimnasios'],
  ejercicio: ['Gimnasios', 'Deportes'],
  deporte: ['Deportes'],
  deportes: ['Deportes'],
  fiesta: ['Eventos'],
  evento: ['Eventos'],
  muebles: ['Muebles'],
  sofa: ['Muebles'],
  silla: ['Muebles'],
  hotel: ['Hoteles'],
  hospedaje: ['Hoteles'],
  transporte: ['Transporte'],
  uber: ['Transporte'],
  taxi: ['Transporte'],
  educacion: ['Educación'],
  educación: ['Educación'],
  escuela: ['Educación'],
  curso: ['Educación'],
  seguro: ['Seguros'],
  seguros: ['Seguros'],
  bicicleta: ['Bicicletas'],
  bici: ['Bicicletas'],
  flor: ['Florerías'],
  flores: ['Florerías'],
  optica: ['Ópticas'],
  óptica: ['Ópticas'],
  lentes: ['Ópticas'],
  foto: ['Fotografía'],
  imprenta: ['Imprentas'],
  papeleria: ['Papelerías'],
  juguete: ['Jugueterías'],
  libro: ['Librerías'],
  vino: ['Vinaterías'],
  tortilla: ['Tortillerías'],
  carne: ['Carnicerías'],
  verdura: ['Verdulerías'],
  abarrotes: ['Abarrotes'],
  tecnologia: ['Tecnología'],
  tecnología: ['Tecnología'],
  computadora: ['Tecnología'],
  laptop: ['Tecnología'],
  celular: ['Tecnología'],
  lavanderia: ['Lavanderías'],
  lavandería: ['Lavanderías'],
  artesanias: ['Artesanías'],
  artesanías: ['Artesanías'],
  spa: ['Spa', 'Belleza'],
};

export function categoryIcon(name: string): LucideIcon {
  return CATEGORIES.find((c) => c.name === name)?.icon ?? OtherIcon;
}
